import { Link } from 'react-router-dom';
import {
  PlusCircle,
  BarChart2,
  AlertTriangle,
  CheckCircle,
  Sparkles,
  Clock,
} from 'lucide-react';
import Button from '../components/ui/Button';
import Card from '../components/ui/Card';
import EmptyState from '../components/ui/EmptyState';
import './DashboardPage.css';

/* ── Stat card ──────────────────────────────────────── */
function StatCard({ icon, iconTheme, label, value, note }) {
  const isEmpty = value === null || value === undefined;
  return (
    <Card className="stat-card">
      <div className="stat-card__header">
        <div className={`stat-card__icon stat-card__icon--${iconTheme}`} aria-hidden="true">
          {icon}
        </div>
      </div>
      <div className={`stat-card__value${isEmpty ? ' stat-card__value--empty' : ''}`}>
        {isEmpty ? '—' : value}
      </div>
      <div>
        <div className="stat-card__label">{label}</div>
        {note && <div className="stat-card__note">{note}</div>}
      </div>
    </Card>
  );
}

/* ── Step card ──────────────────────────────────────── */
function StepCard({ step, title, description }) {
  return (
    <Card className="step-card" padding="sm">
      <div className="step-card__number" aria-hidden="true">{step}</div>
      <div className="step-card__title">{title}</div>
      <p className="step-card__desc">{description}</p>
    </Card>
  );
}

/* ── Dashboard page ─────────────────────────────────── */
export default function DashboardPage() {
  return (
    <div className="dashboard">

      {/* ── Hero ── */}
      <section className="dashboard__hero" aria-labelledby="hero-heading">
        <div className="dashboard__hero-text">
          <p className="dashboard__hero-eyebrow">AI-Powered SEO Platform</p>
          <h2 id="hero-heading" className="dashboard__hero-title">
            Analyse. Diagnose.<br />Optimise.
          </h2>
          <p className="dashboard__hero-sub">
            Crawl any website, detect technical and on-page SEO issues, calculate
            an SEO health score, and receive AI-powered fix recommendations — all
            in a single audit.
          </p>
          <div className="dashboard__hero-actions">
            <Button
              as={Link}
              to="/audit/new"
              variant="primary"
              size="lg"
              icon={<PlusCircle size={16} strokeWidth={2} />}
            >
              Start New Audit
            </Button>
            <Button
              as={Link}
              to="/audits"
              variant="ghost"
              size="lg"
              style={{ color: 'rgba(255,255,255,0.65)' }}
            >
              View history
            </Button>
          </div>
        </div>

        {/* Score ring illustration */}
        <div className="dashboard__hero-visual" aria-hidden="true">
          <div className="dashboard__score-ring">
            <div className="dashboard__score-ring-inner">
              <span className="dashboard__score-placeholder">—</span>
              <span className="dashboard__score-label">Score</span>
            </div>
          </div>
        </div>
      </section>

      {/* ── Overview stats ── */}
      <section aria-labelledby="stats-heading">
        <div className="dashboard__section-header">
          <h2 id="stats-heading" className="dashboard__section-title">Overview</h2>
        </div>
        <div className="dashboard__stats">
          <StatCard
            icon={<BarChart2 size={18} strokeWidth={1.75} />}
            iconTheme="indigo"
            label="Audits Run"
            value={null}
            note="Run your first audit to see metrics"
          />
          <StatCard
            icon={<AlertTriangle size={18} strokeWidth={1.75} />}
            iconTheme="orange"
            label="Issues Detected"
            value={null}
            note="Issues from all audits"
          />
          <StatCard
            icon={<CheckCircle size={18} strokeWidth={1.75} />}
            iconTheme="emerald"
            label="Average SEO Score"
            value={null}
            note="Across all completed audits"
          />
          <StatCard
            icon={<Sparkles size={18} strokeWidth={1.75} />}
            iconTheme="violet"
            label="AI Recommendations"
            value={null}
            note="Generated by the AI engine"
          />
        </div>
      </section>

      {/* ── How it works ── */}
      <section aria-labelledby="how-heading">
        <div className="dashboard__section-header">
          <h2 id="how-heading" className="dashboard__section-title">How it works</h2>
        </div>
        <div className="dashboard__steps">
          <StepCard
            step={1}
            title="Enter a URL"
            description="Paste any website URL. The crawler will respect robots.txt and page/depth limits you configure."
          />
          <StepCard
            step={2}
            title="Automated analysis"
            description="The backend crawls pages and runs technical and on-page SEO checks: titles, headings, meta tags, HTTPS, canonical, sitemap, and more."
          />
          <StepCard
            step={3}
            title="Review your score"
            description="Get a calculated SEO health score with severity-weighted issue counts and a grade from Critical to Excellent."
          />
          <StepCard
            step={4}
            title="AI recommendations"
            description="The AI engine interprets detected issues and generates prioritised, actionable fix recommendations."
          />
        </div>
      </section>

      {/* ── Recent audits ── */}
      <section aria-labelledby="recent-heading">
        <div className="dashboard__section-header">
          <h2 id="recent-heading" className="dashboard__section-title">Recent Audits</h2>
        </div>
        <Card className="dashboard__recent">
          <EmptyState
            icon={<Clock size={22} strokeWidth={1.5} />}
            title="No audits yet"
            description="Start your first SEO audit to analyse a website's technical health, on-page factors, and SEO score."
            actions={
              <Button
                as={Link}
                to="/audit/new"
                variant="primary"
                icon={<PlusCircle size={14} strokeWidth={2} />}
              >
                Start New Audit
              </Button>
            }
          />
        </Card>
      </section>

    </div>
  );
}
