import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Sparkles, PlusCircle, AlertCircle, ArrowLeft } from 'lucide-react';
import { auditsApi } from '../api/audits';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';
import Badge from '../components/ui/Badge';
import EmptyState from '../components/ui/EmptyState';
import './PlaceholderPage.css';
import './AuditResultPage.css';

/* ── Placeholder shown from /recommendations (no audit ID) ─────── */
function RecommendationsPlaceholder() {
  return (
    <div className="placeholder-page">
      <div className="placeholder-page__header">
        <h2 className="placeholder-page__title">AI Recommendations</h2>
        <p className="placeholder-page__subtitle">
          Prioritised, actionable recommendations generated by the AI engine.
        </p>
      </div>
      <Card>
        <EmptyState
          icon={<Sparkles size={22} strokeWidth={1.5} />}
          title="No recommendations yet"
          description="After completing an audit, you can view tailored AI recommendations for the detected issues."
          actions={
            <Button as={Link} to="/audit/new" variant="primary" icon={<PlusCircle size={14} strokeWidth={2} />}>
              Start New Audit
            </Button>
          }
        />
      </Card>
    </div>
  );
}

/* ── Audit-specific recommendations page (/audit/:id/recommendations) */
function AuditRecommendations({ id }) {
  const [recommendations, setRecommendations] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchExisting = async () => {
      setIsLoading(true);
      setError(null);
      try {
        const res = await auditsApi.getRecommendations(id);
        if (res?.recommendations) {
          setRecommendations(res.recommendations);
        }
      } catch (err) {
        // 404 means not yet generated — leave empty, show generate button
        if (err.status !== 404) {
          setError(err.message || 'Failed to load recommendations.');
        }
      } finally {
        setIsLoading(false);
      }
    };

    fetchExisting();
  }, [id]);

  const handleGenerate = async () => {
    setIsGenerating(true);
    setError(null);
    try {
      const res = await auditsApi.generateRecommendations(id);
      if (res?.recommendations) {
        setRecommendations(res.recommendations);
      }
    } catch (err) {
      setError(err.message || 'Failed to generate AI recommendations.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="placeholder-page">
      {/* Header */}
      <div
        className="placeholder-page__header"
        style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}
      >
        <div>
          <h2 className="placeholder-page__title">AI Recommendations</h2>
          <p className="placeholder-page__subtitle">Audit #{id}</p>
        </div>
        <Button as={Link} to={`/audit/${id}`} variant="secondary" icon={<ArrowLeft size={16} />}>
          Back to Audit
        </Button>
      </div>

      {/* Error alert */}
      {error && (
        <div className="error-alert" role="alert" style={{ marginBottom: 'var(--space-4)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)' }}>
            <AlertCircle size={16} />
            {error}
          </div>
        </div>
      )}

      {/* States */}
      {isLoading ? (
        <div className="loading-view">
          <div className="loading-spinner" />
          <div className="loading-text">Loading recommendations...</div>
        </div>
      ) : recommendations.length === 0 ? (
        <Card>
          <EmptyState
            icon={<Sparkles size={32} strokeWidth={1.5} color="var(--color-brand-500)" />}
            title="Generate AI Recommendations"
            description="Our AI engine can analyse the issues found in this audit and provide prioritised, actionable steps to fix them."
            actions={
              <Button variant="primary" onClick={handleGenerate} loading={isGenerating}>
                Generate Now
              </Button>
            }
          />
        </Card>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-4)' }}>
          {recommendations.map((rec, idx) => (
            <Card key={idx} padding="md" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
              {/* Title row */}
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 'var(--space-4)' }}>
                <h3 style={{ fontSize: 'var(--font-size-lg)', fontWeight: 'var(--font-weight-semibold)', color: 'var(--color-text-primary)' }}>
                  {rec.title}
                </h3>
                <Badge severity={rec.severity} />
              </div>

              {/* Issue type */}
              <div style={{ fontSize: 'var(--font-size-sm)', color: 'var(--color-text-secondary)', display: 'flex', gap: 'var(--space-2)', alignItems: 'center' }}>
                <span style={{ fontWeight: 'var(--font-weight-medium)', color: 'var(--color-text-primary)' }}>Issue type:</span>
                <span style={{ fontFamily: 'var(--font-mono, monospace)', background: 'var(--color-neutral-100)', padding: '1px 6px', borderRadius: 'var(--radius-sm)' }}>{rec.issue_type}</span>
              </div>

              {/* Explanation */}
              <div>
                <strong style={{ display: 'block', marginBottom: 'var(--space-1)', fontSize: 'var(--font-size-sm)', color: 'var(--color-text-primary)' }}>Explanation</strong>
                <p style={{ fontSize: 'var(--font-size-base)', color: 'var(--color-text-secondary)', lineHeight: '1.6' }}>{rec.explanation}</p>
              </div>

              {/* Recommendation + Suggested action */}
              <div style={{ background: 'var(--color-neutral-50)', padding: 'var(--space-4)', borderRadius: 'var(--radius-md)', border: '1px solid var(--color-border)', display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
                <div>
                  <strong style={{ display: 'block', marginBottom: 'var(--space-1)', fontSize: 'var(--font-size-sm)', color: 'var(--color-text-primary)' }}>Recommendation</strong>
                  <p style={{ fontSize: 'var(--font-size-base)', color: 'var(--color-text-primary)', lineHeight: '1.6' }}>{rec.recommendation}</p>
                </div>
                <div>
                  <strong style={{ display: 'block', marginBottom: 'var(--space-1)', fontSize: 'var(--font-size-sm)', color: 'var(--color-text-primary)' }}>Suggested Action</strong>
                  <p style={{ fontSize: 'var(--font-size-sm)', color: 'var(--color-text-secondary)', lineHeight: '1.6' }}>{rec.suggested_action}</p>
                </div>
              </div>

              {/* Optional example */}
              {rec.example && (
                <div>
                  <strong style={{ display: 'block', marginBottom: 'var(--space-1)', fontSize: 'var(--font-size-sm)', color: 'var(--color-text-primary)' }}>Example</strong>
                  <pre style={{ background: 'var(--color-neutral-900)', color: '#e2e8f0', padding: 'var(--space-3)', borderRadius: 'var(--radius-md)', fontSize: 'var(--font-size-sm)', overflowX: 'auto', lineHeight: '1.5' }}>
                    {rec.example}
                  </pre>
                </div>
              )}
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

/* ── Route entry point — decides which view to render ────────── */
export default function RecommendationsPage() {
  const { id } = useParams();

  if (!id) {
    return <RecommendationsPlaceholder />;
  }

  return <AuditRecommendations id={id} />;
}
